vm.swappiness=150
vm.page-cluster=0
vm.vfs_cache_pressure=50

vm.dirty_background_ratio=5
vm.dirty_ratio=15

vm.max_map_count=2147483642

fs.inotify.max_user_watches=524288
fs.inotify.max_user_instances=1024

kernel.nmi_watchdog=0

net.ipv4.tcp_ecn=1
net.core.default_qdisc=fq
